[build]
  command = "npm run build"
  publish = "out" # or ".next" depending on your setup

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true
